[package]
name = "client"
version = "0.1.0"
edition = "2024"
authors = ["Pinhole Team"]
repository = "https://github.com/RafeLoya/pinhole"
description = "Client for terminal-based video call service"

[dependencies]
common = { path = "../common" }

tokio = { version = "1.40", features = ["full"] }
clap = { version = "4.5.37", features = ["derive"] }
rand = "0.9.1"

[[bin]]
name = "client"
