[package]
name = "final-project-group4_s25"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies.nokhwa]
version = "0.10.0"
# Use the native input backends, enable WGPU integration
features = ["input-native", "output-wgpu"]