# build:            `docker compose -f .devcontainer/local.docker-compose.yml up --build`
# enter container:  `docker compose -f .devcontainer/local.docker-compose.yml run --rm server /bin/bash`
# teardown:         `docker compose -f .devcontainer/local.docker-compose.yml down`

services:
  server:
    build:
      context: ../
      dockerfile: .devcontainer/server.Dockerfile
      platforms:
        - linux/arm64
    image: rust-server-local
    container_name: rust-server-dev
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      - RUST_LOG=debug
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - MAX_CONNECTIONS=100
    volumes:
      - ../server:/app/server
      - ../common:/app/common
    restart: unless-stopped  # Automatically restart if it crashes
    networks:
      - app-network
    platform: linux/arm64

networks:
  app-network:
    driver: bridge
