name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [client, server]
    steps:
    - uses: actions/checkout@v4

    - name: Build ${{ matrix.project }}
      working-directory: ./${{ matrix.project }}
      run: cargo build --verbose

    - name: Run tests for ${{ matrix.project }}
      working-directory: ./${{ matrix.project }}
      run: cargo test --verbose
